plugins {
    id 'com.android.application'
}


android {
    compileSdk {
        version = release(37) {
            minorApiLevel = 1
        }
    }
    buildToolsVersion = '37.0.0'

    defaultConfig {
        applicationId = "com.draco.ladb"
        minSdk = 26
        targetSdk = 37
        versionCode = 56
        versionName = "2.7"

        resConfigs "en", "ru", "zh-rCN"
    }

    signingConfigs {
        release {
            storeFile = file('LADB.jks')
            storePassword = 'LADB'
            keyAlias = 'ladb'
            keyPassword = 'LADB'

            enableV2Signing = true
            enableV3Signing = true
        }
    }

    splits {
        abi {
            enable = true
            reset()
            include 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64'
            universalApk = true
        }
    }

    buildTypes {
        release {
            minifyEnabled = true
            shrinkResources = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

            signingConfig = signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }

    buildFeatures {
        buildConfig = true
        viewBinding = true
    }

    namespace = 'com.draco.ladb'
}

dependencies {
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.11.0'

    implementation 'androidx.core:core-ktx:1.19.0'
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'androidx.preference:preference-ktx:1.2.1'
    implementation 'androidx.fragment:fragment-ktx:1.9.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.11.0'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.11.0'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.11.0'

    implementation("androidx.activity:activity-ktx:1.13.0")

    implementation 'com.google.android.material:material:1.14.0'
}
